// 소개 페이지의 내용 전부. 새 서브프로젝트를 닫으면 여기만 고친다 —
// 순서는 main 저장소의 site/README.md "갱신" 절에 있다.
//
// 표기: 문자열 안의 `x`는 <code>, [x]는 <kbd>로 그려진다(app.js의 rich).
window.TARS = {
  // 기준일. 페이지의 "기준" 글자와 NEW 판정이 이 날을 본다.
  asOf: '2026-10-10',
  latest: 'Gate Parallel (GP-M0~M2)',
  // 기준일에서 이 날수 안에 끝난 기능과 서브프로젝트에 NEW가 붙는다.
  newWithinDays: 2,

  stats: {
    commits: 946,       // git rev-list --count main
    since: '2026-08-01',
    chains: 22,         // check.sh의 CHAINS
    zigKLines: 34,      // init · terminal · tars-config의 .zig 줄 수 / 1000
  },

  // 부팅 사슬 애니메이션: [켜질 칸(0 ISO … 5 셸), 머리, 본문].
  // 본문은 site/capture.sh가 찍은 부팅의 serial.log에서 그대로 옮겼다.
  serial: [
    [0, 'iso', 'out/tars.iso — El Torito · GPT hybrid'],
    [1, 'limine', 'kernel bzImage · module initrd.cpio'],
    [2, '[    0.000000]', 'Linux version 6.18.42 (x86_64-linux-gnu-gcc 14.2.0)'],
    [2, '[    3.457510]', 'Run /init as init process'],
    [3, 'tars-init:', 'starting as PID 1'],
    [3, 'tars-init:', 'mounted devtmpfs at /dev'],
    [3, 'tars-init:', 'lo up'],
    [3, 'tars-init:', 'config shell=fish keyboard=apple hangul=shin_pcs latin=qwerty'],
    [4, 'terminal:', 'grid 123x37 (fb 1024x640)'],
    [4, 'terminal:', 'hangul layout=shin_pcs latin=qwerty'],
    [5, 'terminal:', 'spawned child pid 40 (/usr/bin/fish)'],
    [5, 'terminal:', 'render> first frame 46347us'],
  ],

  // 끝낸 서브프로젝트: [끝난 날, 이름, 약칭, 한 줄]. 순서는 상관없다(날짜로 정렬).
  timeline: [
    ['2026-08-07', 'Boot Foundation', 'BF', '직접 빌드한 커널을 QEMU에서 띄우고 PID 1이 자식을 감독한다'],
    ['2026-08-08', 'Display Foundation', 'DF', '프레임버퍼에 픽셀을 직접 찍는다'],
    ['2026-08-13', 'Terminal Foundation', 'TF', 'PTY 위의 터미널이 글자를 그린다'],
    ['2026-08-13', 'Zig Migration', 'ZM', 'Rust를 Zig로 옮겼다. 이제 Rust는 없다'],
    ['2026-08-15', 'Config Persistence', 'CP', 'ext2 디스크의 `key=value` 설정을 부팅 사이에 읽는다'],
    ['2026-08-19', 'Input Policy', 'IP', 'evdev 코드를 셸이 아는 바이트로 번역한다'],
    ['2026-08-20', 'Power Management', 'PM', '시그널로 끄고 되살린다'],
    ['2026-08-22', 'Hardware Discovery', 'HD', '키보드를 capability로 찾고 전원 버튼에 응답한다'],
    ['2026-08-24', 'Terminal Rendering', 'TR', '색 · 스크롤 · 오프셋을 `vt.zig`가 확정한다'],
    ['2026-08-26', 'Copy Mode', 'CM', '스크롤백 위의 vim modal 선택과 [⌘V]'],
    ['2026-08-27', 'Copy Navigation', 'CN', '단어 이동 [w] [b]와 스크롤백 검색 [/] [n] [N]'],
    ['2026-08-28', 'Copy Search Feedback', 'CS', '매치 하이라이트 · 검색 기록 · "못 찾음" 메시지'],
    ['2026-08-29', 'Gate Latency', 'GL', '루트 게이트 54분 15초 → 16분'],
    ['2026-08-30', 'Search Position', 'SP', '현재 매치를 밝은 앰버로, 오버레이에 `/needle [3/12]`'],
    ['2026-08-30', 'Render Cost', 'RC', '한 프레임의 84.7%가 `fill`이라는 것을 재기만 했다'],
    ['2026-08-31', 'Carryover Cleanup', 'CC', '이월 숙제 셋을 없앴다'],
    ['2026-09-01', 'Hangul Input', 'HI', '한글 자판 넷과 영문 자판 둘, 한/영 전환 키 넷'],
    ['2026-09-09', 'Input Status', 'IS', '화면 맨 아래의 상태 줄 — 한/영 · 자판 · 대문자 잠금'],
    ['2026-09-09', 'Search Hangul', 'SH', 'copy mode 검색창에서 한글을 친다'],
    ['2026-09-09', 'Find Paste', 'FP', 'copy mode에서 잡은 글자를 [/] 프롬프트에 붙인다'],
    ['2026-09-10', 'Real Machine', 'RM', '일반 x86_64 노트북에서 뜬다 — UEFI · simpledrm · USB 키보드 · NVMe'],
    ['2026-09-11', 'Userland Tools', 'UT', '게스트에 도구 65개, `PATH`로 이름이 손에 닿는다'],
    ['2026-09-11', 'Shell Config', 'SC', '`shell_config`가 rc를 켜고 끄고, 탈출로 둘'],
    ['2026-09-12', 'Shell Memory', 'SM', '`zoxide` · `fzf`와 히스토리가 부팅을 넘는다'],
    ['2026-09-12', 'Gate Accuracy', 'GA', '게이트가 거짓을 말하던 일곱 자리를 없앴다'],
    ['2026-09-12', 'Shell History Durability', 'SD', 'zsh 히스토리가 전원 버튼과 함께 사라지지 않는다'],
    ['2026-09-12', 'Bash History Durability', 'BH', 'bash도 같다. 덤으로 `/dev/fd`'],
    ['2026-09-12', 'Bash Boot', 'BB', '`shell=bash`로 뜨는 부팅을 게이트가 본다'],
    ['2026-09-13', 'Shutdown Latency', 'SL', '끄는 데 2.9초 걸리던 것이 0.13초'],
    ['2026-09-14', 'Guest Network', 'NW', '`net=dhcp`가 게스트에 주소를 붙인다'],
    ['2026-09-14', 'Inbound Network', 'IN', '게스트가 연 포트에 바깥에서 붙는다'],
    ['2026-09-19', 'Time Sync', 'TS', '부팅에 시계를 맞추고 `timezone`으로 읽는다'],
    ['2026-09-19', 'Shell Tools', 'ST', 'eza 별칭 넷과 `/config/gitconfig`'],
    ['2026-09-19', 'Terminal Queries', 'TQ', '자식의 질의(커서 위치 · 상태 보고)에 답한다'],
    ['2026-09-23', 'Disk Install', 'DI', '`tars-install`이 내장 디스크에 깔고 USB 없이 뜬다'],
    ['2026-09-26', 'Disk Install Carryover', 'DC', '늦게 생기는 설정 파티션을 기다리는 등 작은 것 다섯'],
    ['2026-09-26', 'Time Discipline', 'TD', '시계는 chronyd가, drift는 부팅을 넘는다'],
    ['2026-09-26', 'Wired NIC', 'WN', '노트북형 유선 드라이버 여섯과 USB 동글 셋'],
    ['2026-09-26', 'Loopback', 'LB', '`localhost`와 `*.localhost`가 풀린다'],
    ['2026-09-27', 'Firewall', 'FW', '`firewall=on`과 사람이 쓰는 `nftables.d`'],
    ['2026-09-27', 'Boot Services', 'SV', '`/config/services.d`를 PID 1이 띄우고 감독한다. 첫 세입자 sshd'],
    ['2026-09-27', 'Service Control', 'CT', '`tars-service` status · stop · start · restart'],
    ['2026-09-27', 'Daemon Supervision', 'DS', 'dhcpcd와 chronyd도 감독 목록에'],
    ['2026-09-28', 'Wireless', 'WL', '노트북 내장 무선 — Intel · Realtek · MediaTek · Qualcomm'],
    ['2026-09-28', 'USB Wireless', 'UW', 'USB 무선 동글 열하나'],
    ['2026-10-03', 'Terminal Graphics', 'TG', 'kitty graphics 이미지를 그린다'],
    ['2026-10-03', 'Copy Indicator', 'CI', 'copy mode 동안 상태 줄에 `COPY`'],
    ['2026-10-04', 'Workspace Panes', 'WP', '워크스페이스 아홉 × 패널 여덟, 키는 iTerm2 그대로'],
    ['2026-10-04', 'Cursor Shape', 'CU', 'vim의 insert는 bar, replace는 underline, normal은 block'],
    ['2026-10-04', 'Guest Ergonomics', 'GE', '`which`와 플러그인 없는 모던 vimrc'],
    ['2026-10-04', 'Paste Ergonomics', 'PE', 'bracketed paste — 여러 줄을 붙여도 Enter 전에는 안 돈다'],
    ['2026-10-05', 'Pointer Devices', 'PD', '마우스와 터치패드, 끌어서 복사, 마우스 보고'],
    ['2026-10-05', 'Escape Latin', 'EL', '한글을 치다 Esc를 누르면 영문으로'],
    ['2026-10-05', 'Clipboard Scope', 'CB', '패널과 워크스페이스를 건너는 클립보드 하나'],
    ['2026-10-06', 'Audio Devices', 'AU', '스피커 · 마이크 · 헤드폰 잭 · USB 헤드셋 · DSP 마이크'],
    ['2026-10-06', 'Voice Dictation', 'VD', '오른쪽 [⌘] 두 번으로 받아쓰기'],
    ['2026-10-07', 'Config Tool', 'TC', '`tars-config`가 설정을 보고 · 고치고 · 재부팅 없이 적용한다'],
    ['2026-10-07', 'Atomic Log Lines', 'AL', '로그 한 줄이 write 한 번'],
    ['2026-10-09', 'Battery Status', 'BS', '상태 줄 오른쪽 끝의 배터리 잔량'],
    ['2026-10-10', 'Gate Parallel', 'GP', '루트 게이트 1시간 01분 → 9분 51초, 체인을 동시에'],
  ],

  // 전체 기능: 갈래마다 [이름, 설명, 끝난 날]. 끝난 날은 timeline의 날짜와 같게.
  features: [
    {
      title: '부팅 · 하드웨어',
      note: '노트북에 USB로 꽂아 띄우는 것이 목표다. GPU 가속 · 밝기 · 외부 모니터 · 절전(S3) · Bluetooth · HDMI 오디오 · IPv6는 아직 없다.',
      items: [
        ['하이브리드 ISO `out/tars.iso`', 'BIOS와 UEFI 항목이 한 ISO에. `dd`로 USB에 그대로 쓴다. 부트로더는 Limine, Secure Boot는 끈다', '2026-09-10'],
        ['화면 — simpledrm · virtio-gpu', '펌웨어가 준 프레임버퍼를 패널 기본 해상도로 쓴다. 격자 크기는 KMS가 준 크기에서 정한다', '2026-09-10'],
        ['저장장치', 'NVMe · SATA AHCI · USB storage · virtio-blk. 파일시스템은 ext2 · VFAT · ISO9660', '2026-09-10'],
        ['키보드', 'PS/2와 USB HID. 이름이 아니라 capability로 찾고, 늦게 잡히는 USB 키보드는 3초까지 기다린다', '2026-09-10'],
        ['전원 버튼', '누르면 정상 종료. SIGTERM은 끄기, SIGINT와 [Ctrl+Alt+Del]은 재부팅', '2026-08-22'],
        ['빠른 종료', 'SIGTERM 다음 SIGHUP도 보낸다. 콘솔 셸이 2.9초 끌던 것이 0.13초', '2026-09-13'],
        ['배터리 · AC', 'ACPI 배터리와 어댑터를 읽어 상태 줄에 잔량을 그린다', '2026-10-09'],
        ['터치패드 · 마우스 커널', 'PS/2(Synaptics · Elantech · ALPS 등) · SMBus · I2C-HID · Intel THC · HID multitouch', '2026-10-05'],
        ['오디오 커널', 'HDA 코덱 여덟 · Intel SOF(CNL~PTL) · AMD ACP · USB Audio, firmware 42개', '2026-10-06'],
      ],
    },
    {
      title: 'init — PID 1',
      note: 'Zig로 쓴 `/init`. 마운트 · 설정 · 네트워크 · 감독 · 전원을 맡는다.',
      items: [
        ['설정 디스크 `/config`', 'ext2 라벨이 `tars-`로 시작하는 첫 장치를 붙인다. 없어도 부팅은 되고 설정만 매번 사라진다', '2026-09-10'],
        ['첫 부팅 seed', '`tars.conf` · 셸 rc 셋 · `gitconfig` · `vimrc`를 없을 때만 깐다. 사람이 고친 파일은 안 덮는다', '2026-10-04'],
        ['자식 감독', 'terminal · 콘솔 셸 · dhcpcd · chronyd · wpa_supplicant · 서비스. 죽으면 1초 뒤 다시, 10초 안에 세 번이면 포기', '2026-09-27'],
        ['rc 탈출로', '콘솔 셸이 빨리 세 번 죽으면 rc 없이 한 번 더 띄운다', '2026-09-11'],
        ['커널 cmdline `tars.noconfig`', '셸 rc를 안 읽는다. `tars.conf`보다 우선', '2026-09-11'],
        ['부팅 서비스 `/config/services.d/`', '실행 파일을 이름순으로 여덟까지 띄우고 감독한다. `.`으로 시작하는 이름은 건너뛴다', '2026-09-27'],
        ['sshd', '`services.d/sshd` 링크 하나와 `ssh/authorized_keys`로 켜진다. 키로만 root 로그인, 세션은 콘솔과 같은 셸 · env', '2026-09-27'],
        ['loopback', '설정보다 먼저 `lo`를 올린다. `localhost`와 `아무거나.localhost`가 127.0.0.1', '2026-09-26'],
        ['셸 환경', '`PATH` · `TZ` · `XDG_DATA_HOME=/config/xdg` · 히스토리 파일이 `/config`에', '2026-09-12'],
        ['오디오 담당', '부팅에 믹서를 켜고 끌 때 `/config/asound.state`에 저장. 1초마다 기본 카드를 고른다 — 재생은 가장 큰 번호, 녹음은 USB 마이크 → 내장 DMIC → 장치 0', '2026-10-06'],
        ['원자적 로그 줄', 'init과 terminal의 시리얼 로그 한 줄이 write 한 번이라 서로 끼어들지 않는다', '2026-10-07'],
      ],
    },
    {
      title: '설정 — `tars.conf` 키 열둘',
      note: '`/config/tars.conf`의 `key=value`. 모르는 키나 값은 로그만 남기고 기본값을 쓴다. 우선순위는 cmdline > `tars.conf` > 기본값.',
      items: [
        ['`shell`', '`fish` | `bash` | `zsh` — 기본 `fish`', '2026-09-12'],
        ['`keyboard`', '`apple` | `pc` — `pc`는 Alt와 Win을 맞바꿔 Cmd 자리를 맞춘다. 기본 `apple`', '2026-08-19'],
        ['`hangul_layout`', '`dubeol` | `sebeol_3p3` | `shin_p2` | `shin_pcs` — 기본 `shin_pcs`', '2026-09-01'],
        ['`latin_layout`', '`qwerty` | `dvorak` — 기본 `qwerty`', '2026-09-01'],
        ['`hangul_toggle`', '`hangul_key` · `shift_space` · `capslock_tap` · `lctrl_tap`의 콤마 목록, `none`이면 끔. 기본 넷 다', '2026-09-01'],
        ['`esc_latin`', '`on` | `off` — 한글 중 Esc가 영문으로 돌려놓는가. 기본 `on`', '2026-10-05'],
        ['`shell_config`', '`on` | `off` — 셸이 rc를 읽는가. 기본 `on`', '2026-09-11'],
        ['`net`', '`off` | `dhcp` — 기본 `off`', '2026-09-14'],
        ['`ntp`', '`off` | `dhcp` | IPv4 주소 — 기본 `off`', '2026-09-26'],
        ['`timezone`', '`UTC` | IANA 이름(`Asia/Seoul`) — 기본 `UTC`', '2026-09-19'],
        ['`firewall`', '`off` | `on` — 기본 `off`', '2026-09-27'],
        ['`clipboard`', '`shared` | `pane` — 기본 `shared`', '2026-10-05'],
      ],
    },
    {
      title: '`/config`에 사람이 두는 파일',
      note: '홈(`/`)은 tmpfs라 부팅을 넘는 자리는 설정 디스크뿐이다.',
      items: [
        ['`wpa_supplicant.conf`', '있으면 init이 `tars-wifi`(→ wpa_supplicant)를 감독한다', '2026-09-28'],
        ['`services.d/*`', '부팅 서비스. sshd는 `/etc/tars/services/sshd`로 가는 링크', '2026-09-27'],
        ['`ssh/authorized_keys`', 'root 키 로그인. 호스트 키는 처음에 저절로 생긴다', '2026-09-27'],
        ['`nftables.d/*.nft`', '방화벽에서 열 포트를 nftables 문법으로. 틀리면 기본 규칙만 올린다', '2026-09-27'],
        ['`chrony.d/*.conf`', 'chrony 서버를 이름으로. 배운 drift는 `chrony.drift`로 부팅을 넘는다', '2026-09-26'],
        ['`gitconfig` · `vimrc`', '`/.gitconfig` · `/.vimrc` 링크의 대상', '2026-10-04'],
        ['`bashrc` · `zshrc` · `fish.config`', '셸 rc. eza 별칭 넷(`ls` `ll` `la` `lt`)과 zoxide · fzf 훅이 seed에', '2026-09-19'],
        ['`bash_history` · `zsh_history` · `xdg/`', '히스토리와 zoxide · fish 데이터. 전원 버튼에도 명령마다 남는다', '2026-09-12'],
        ['`asound.state`', '볼륨이 부팅을 넘는다', '2026-10-06'],
        ['`dictation.conf` · `groq.key`', '받아쓰기 설정 키 여덟과 Groq API 키. 기록은 `dictation.jsonl`', '2026-10-06'],
      ],
    },
    {
      title: '명령',
      items: [
        ['`tars-config`', '인자 없이: 지금 설정을 init이 읽는 모양으로, 실제로 쓰이는 값과 다르면 알린다', '2026-10-07'],
        ['`tars-config get` · `set KEY=VALUE` · `reset` · `list` · `check`', '`tars.conf`의 줄 하나만 바꾼다. 값의 판정은 init의 파서가', '2026-10-07'],
        ['`tars-config reload`', '재부팅 없이 적용 — net · ntp · firewall · services.d · 무선은 곧바로, 셸 키는 다음 셸부터', '2026-10-07'],
        ['`tars-config reload terminal`', '화면을 새 값으로 다시 띄운다(패널과 클립보드는 사라진다)', '2026-10-07'],
        ['`tars-config wifi` · `ssh` · `ssh-key` · `firewall` · `dictation`', '무선 접속 · sshd 켜고 끄기 · 공개 키 추가 · 포트 열고 닫기 · 받아쓰기 키와 설정', '2026-10-07'],
        ['`tars-service status` · `stop` · `start` · `restart`', '`/run/tars/init.sock`으로 PID 1에게. stop은 프로세스 그룹에 SIGTERM, 3초 뒤 SIGKILL', '2026-09-27'],
        ['`tars-install <디스크>`', 'GPT에 256MiB ESP와 1GiB 설정 파티션. 이미 깔린 디스크는 부트 파일만 갱신하고 설정은 남긴다. UEFI 전용', '2026-09-23'],
        ['`tars-install --wipe` · `--yes`', '설정까지 통째로 지운다 · 확인 `YES`를 건너뛴다', '2026-09-23'],
        ['`tars-dictate`', '말하고 [Ctrl+C]. 셸에서 직접 받아쓰기', '2026-10-06'],
      ],
    },
    {
      title: '터미널 화면',
      note: 'VT 해석은 ghostty-vt, 그리기는 우리 코드다. `TERM=xterm-256color`, 폰트 unifont.',
      items: [
        ['256색과 OSC 10/11', '기본 배경 `#102030`. 자식이 전경 · 배경을 바꿀 수 있다', '2026-08-24'],
        ['스크롤백', '1000줄. 뷰포트를 올렸다 내려도 자식 출력은 그대로 이어진다', '2026-08-24'],
        ['kitty graphics', 'RGB · RGBA · PNG(`f=100`, stb_image). 알파 합성과 z 순서', '2026-10-03'],
        ['커서 모양 DECSCUSR', 'block · bar · underline. 게스트 vim은 insert bar, replace underline', '2026-10-04'],
        ['bracketed paste', '자식이 모드 2004를 켰으면 붙인 글자를 `ESC[200~` · `ESC[201~`로 감싼다', '2026-10-04'],
        ['질의 응답', '커서 위치(`ESC[6n`) · 상태 보고 · 픽셀 크기(`CSI 14t`). 제목 보고는 보안상 끔', '2026-09-19'],
        ['마우스 보고', '모드 9 · 1000 · 1002 · 1003, 1007(대체 화면의 휠 → 화살표)', '2026-10-05'],
        ['워크스페이스 · 패널', '워크스페이스 아홉 × 패널 여덟. 마지막 패널을 닫으면 terminal이 끝나고 init이 새로 띄운다', '2026-10-04'],
        ['클립보드', 'terminal 전체에 하나 — 한 패널에서 잡은 것을 다른 워크스페이스에 붙인다. `clipboard=pane`이면 패널마다', '2026-10-05'],
      ],
    },
    {
      title: '상태 줄',
      note: '화면 맨 아래 여백 한 줄. 왼쪽부터 차례로.',
      items: [
        ['`한` / `EN`', '한/영 상태', '2026-09-09'],
        ['자판 이름', '두벌식 · 공세벌 3-P3 · 신세벌 P2 · 신세벌 PCS, 그리고 쿼티 · 드보락', '2026-09-09'],
        ['`CAPS`', '대문자 잠금. 켜짐과 꺼짐을 색으로', '2026-09-09'],
        ['`W1`~`W9`', '워크스페이스가 둘 이상일 때', '2026-10-04'],
        ['`COPY`', 'copy mode에 있는 동안. 전용 색', '2026-10-03'],
        ['받아쓰기 낱말', '`REC` · `WAIT` · `NO MIC` · `NO KEY` · `FAILED` · `PASSWORD` · `NO PANE`', '2026-10-06'],
        ['배터리 칸', '오른쪽 끝 폭 4(`100%` · ` 50%` · `  ?%`). 방전 중 회색, 어댑터 초록, 15% 이하 빨강. 배터리가 없으면 칸도 없다', '2026-10-09'],
      ],
    },
    {
      title: '단축키',
      note: 'Cmd는 Apple 키보드의 Cmd, `keyboard=pc`면 Alt 자리다. copy mode 안에서는 패널 키가 안 먹는다.',
      items: [
        ['[⌘D] · [⌘⇧D]', '오른쪽 · 아래에 새 패널', '2026-10-04'],
        ['[⌘W]', '포커스 패널을 닫는다(셸에 SIGHUP)', '2026-10-04'],
        ['[⌘]] · [⌘[]', '다음 · 이전 패널', '2026-10-04'],
        ['[⌘T] · [⌘1]~[⌘9]', '새 워크스페이스 · 그 번호로', '2026-10-04'],
        ['[⌘⇧C]', 'copy mode', '2026-08-26'],
        ['[⌘V]', '붙이기. 어느 모드에서나, 검색 프롬프트에서는 검색어에', '2026-09-09'],
        ['[⌘←] · [⌘→] · [⌘⌫]', '줄 처음 · 끝 · 커서 앞까지 지우기', '2026-08-19'],
        ['[⌥←] · [⌥→] · [⌥⌫] · [⌥Del]', '단어 이동 · 단어 지우기', '2026-08-19'],
        ['[⇧PgUp] · [⇧PgDn] · [⇧Home] · [⇧End]', '스크롤백 한 페이지 · 맨 위 · 맨 아래', '2026-08-24'],
        ['오른쪽 [⌘] 두 번', '받아쓰기 시작 · 끝(300ms 안). 녹음 중 Esc는 취소', '2026-10-06'],
      ],
    },
    {
      title: 'copy mode',
      note: '[⌘⇧C]로 들어가는 스크롤백 위의 vim modal. 아래에 없는 키(`g` `G` `Ctrl+u` `?` 등)는 삼킨다.',
      items: [
        ['[h] [j] [k] [l] · 방향키', '이동', '2026-08-26'],
        ['[w] · [b]', '다음 · 이전 단어', '2026-08-27'],
        ['[/]', '위쪽으로 검색. 한글도 친다, 빈 Enter는 지난 검색어', '2026-09-09'],
        ['[n] · [N]', '다음 · 이전 매치', '2026-08-27'],
        ['매치 표시', '모든 매치는 앰버, 현재 매치는 밝은 앰버, `/needle [3/12]`, 없으면 `: not found`', '2026-08-30'],
        ['[v] · [V]', '글자 · 줄 선택', '2026-08-26'],
        ['[y] · [⌘C]', '복사하고 나온다', '2026-08-26'],
        ['[Esc]', '나온다', '2026-08-26'],
      ],
    },
    {
      title: '한글 입력',
      note: '입력기 데몬 없이 terminal 안의 오토마타가 조합한다.',
      items: [
        ['자판 넷', '두벌식 · 공세벌 3-P3 · 신세벌 P2 · 신세벌 PCS. 물리 키 위치를 쓰므로 드보락이어도 안 바뀐다', '2026-09-01'],
        ['한/영 전환', '한/영 키 · [Shift+Space] · CapsLock 짧게 · 왼쪽 Ctrl 짧게. 길게 누른 CapsLock은 대문자 잠금', '2026-09-01'],
        ['Esc로 영문', '수정키 없는 Esc가 조합을 확정하고 영문으로. Esc 자체는 프로그램에 간다', '2026-10-05'],
        ['조합 중 표시', '조합 중인 글자를 커서 자리에. Backspace는 자모 하나씩', '2026-09-01'],
        ['검색창 한글', 'copy mode 검색에서도 같은 조합', '2026-09-09'],
      ],
    },
    {
      title: '마우스 · 터치패드',
      items: [
        ['핫플러그', 'uevent로 장치를 찾는다. 여덟 대까지, 화살표는 save-under', '2026-10-05'],
        ['클릭 · 끌기', '클릭은 패널 포커스, 끌었다 떼면 선택이 클립보드에. 끄는 중 휠은 선택을 넓힌다', '2026-10-05'],
        ['휠', '포인터 아래 패널의 스크롤백', '2026-10-05'],
        ['마우스 보고', '자식이 켰으면 누름과 움직임을 자식에게. 우리 선택은 [Shift]+끌기', '2026-10-05'],
        ['터치패드', '한 손가락 이동 · 탭 클릭 · 두 손가락 스크롤 · 물리 버튼. 가속과 손바닥 거부는 없다', '2026-10-05'],
      ],
    },
    {
      title: '네트워크',
      items: [
        ['DHCP', '`net=dhcp`면 dhcpcd가 인터페이스를 고른다. 부팅 뒤 꽂은 USB 동글도', '2026-09-26'],
        ['유선', 'virtio-net · e1000e · igc · r8169, USB는 r8152 · ax88179 · ax8817x · cdc_ether · cdc_ncm', '2026-09-26'],
        ['노트북 내장 무선', 'Intel iwlwifi · Realtek rtw88/rtw89 · MediaTek MT7921/7922/7925 · Qualcomm ath11k/ath12k', '2026-09-28'],
        ['USB 무선 동글', 'rtw88 일곱 · rtw89 둘 · MT7921U · MT7925U', '2026-09-28'],
        ['시각', 'chronyd. 서버는 설정의 주소든 DHCP가 알려 준 것이든', '2026-09-26'],
        ['방화벽', '`firewall=on`이면 들어오는 것을 버린다. 받는 것은 lo · 먼저 건 연결의 답 · 사람이 연 포트', '2026-09-27'],
        ['들어오는 연결', '게스트가 연 포트에 바깥에서 붙는다', '2026-09-14'],
      ],
    },
    {
      title: '오디오 · 받아쓰기',
      items: [
        ['`aplay` · `arecord` · `amixer` · `alsamixer` · `speaker-test`', '스피커 · 마이크 · 헤드폰 잭 · USB 헤드셋 · DSP 뒤 내장 마이크', '2026-10-06'],
        ['USB 헤드셋 자동 전환', '꽂은 지 1초 안에 기본 카드가 된다', '2026-10-06'],
        ['받아쓰기', 'arecord → Groq Whisper 전사 → LLM 정리 → 두 번을 누른 패널의 커서 자리에 bracketed paste. Enter는 안 붙인다', '2026-10-06'],
        ['안전장치', '비밀번호 프롬프트에는 넣지 않는다. 정리본이 너무 짧거나 늦거나 실패하면 원문', '2026-10-06'],
        ['`dictation.conf` 키 여덟', '전사 · 정리 URL과 모델, `language`, `max_seconds`, `cleanup`, `cleanup_timeout`', '2026-10-06'],
      ],
    },
    {
      title: '게스트 도구',
      note: '목록은 `kernel/guest_tools.sh` 한 파일. 이름으로 `PATH`에 닿는다.',
      items: [
        ['셸', 'fish · bash · zsh', '2026-09-12'],
        ['모던 CLI', 'eza · bat · fd · rg · sd · tree · duf · ncdu · jq · hyperfine · zoxide · fzf · which', '2026-10-04'],
        ['프로세스', 'ps · top · htop · btop · pgrep · kill · dmesg', '2026-09-11'],
        ['편집 · 개발', 'vim(플러그인 없는 모던 vimrc, `mouse=a`) · git · less · diff', '2026-10-04'],
        ['텍스트 · 파일', 'coreutils 서른여 개 · grep · find · xargs · sed · awk', '2026-09-11'],
        ['네트워크 · 디스크', 'ip · curl · nc · chronyc · nft · ssh-keygen · wpa_cli · iw · sfdisk · mke2fs · mkfs.vfat', '2026-09-28'],
      ],
    },
  ],
};
